### ISSUE TITLE
font Avenir Numbers needs a colon

### ISSUE THREAD

**Issue by b7a** [Hypnootize/hypnotize-hud#18]
Casual rank panel displays as "LEVEL : 1013" due to this.

**Comment by Hypnootize** [comment]
So i was trying to make this work by using the chat_english file instead of using the numbers only font a while ago and then i forgot, could you try the version i just uploaded and see if it shows as "LEVEL 101 : 3" now? I also don't know if the competitive rank is showing only the level or the whole rank name, it seems fine for me tho. 

I wish i could try but I don't have a tier since i barely play casuals or comp matchmaking.

**Comment by b7a** [comment]
Unfortunately, tier level doesn't display, however I created a hotfix last week. https://www.dropbox.com/s/kitmf06534gxqah/fix.zip?dl=0

**Comment by Hypnootize** [comment]
Yeah thats how it used to work before i changed the font to avenir, i guess i'll just go back to that for now, ty!
