### ISSUE TITLE
Casual Rank in scoreboard?

### ISSUE THREAD

**Issue by yeajustwannaplay** [Hypnootize/hypnotize-hud#22]
Changing the medal width value doesn't show the medal so if I can somehow enable them, that would be nice. Thanks

**Comment by Hypnootize** [comment]
For some reason even if you enable them they are gonna stay in the top left corner and I don't know why. Most likely it happens because I pinned most of the elemets together in order to move the whole scoreboard easily but I'm not too sure its if its only that or there is more to it.

I can ask around for a fix but if in order to fix just the medals i need to change the scoreboard look its probably not gonna happen sorry.
