### ISSUE TITLE
Unable to change Damage Text Color

### ISSUE THREAD

**Issue by arcfox72** [Hypnootize/hypnotize-hud#25]
I do not see an option to change the color of the damage text in colors.res, is there any way to do this?

**Comment by Hypnootize** [comment]
If you mean the last damage done (like the one that appears on top of the health) then it can be changed from the colors.res file ve changing "Last Damage Done" "255 255 255 255"

While if you mean the normal floating damage numbers it can only be changed from the ingame advanced options since the last major update. 

Or you can even use the console commands to set the color:
hud_combattext_red
hud_combattext_green
hud_combattext_blue
The values are MIN 0 and MAX 255 so white for example would be: 
hud_combattext_red 255; hud_combattext_green 255; hud_combattext_blue 255
