### ISSUE TITLE
Problem With Quake Font On Hypnotize Hud

### ISSUE THREAD

**Issue by RunawaySheld123** [Hypnootize/hypnotize-hud#33]
![20201102192347_1](https://user-images.githubusercontent.com/26026554/97863318-c0396a00-1d41-11eb-8566-4aade0095103.jpg)

**Comment by Hypnootize** [comment]
Works fine for me with the quake font customization. I don't think it has anything to do with the quake font, to me it seems like you are stuck on an older version of the icon font even tho I don't see how since I changed the name of it. 

You could try going to C:\Windows\Fonts and just delete every font that has my name on it (could be Hypnotie Icons, HypnotizeHud Icons etc...) and also look for anything with sunset in the name and delete it.
Its pretty safe to do since the new fonts in use for icons are directly defined in the hud so you will never need them installed.

Let me know if that fixes anything, if it doesn't I'm not so sure what the problem would be.

**Comment by Hypnootize** [comment]
So I just confirmation by someone else as well that the problem is in fact the old symbols font installed in your system.
I have just now pushed a version of the hud that should fix that so if you could try that version without even deleting the fonts from windows like I told you before and confirm if it does fix the problem would be perfect! ty!
