### ISSUE TITLE
Main Menu Competitive/Casual overlapping

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#34]
When searching for a game and first clicking the competitive button and then clicking the casual button without closing the competitive menu, the casual menu gets drawn under the competitive menu until dismissed by clicking on the emptiness next to the menus.

Since this probably was way too confusing, here's a video ^^

https://user-images.githubusercontent.com/9213561/106151008-2f293200-617c-11eb-94e0-829b88503ca0.mp4

**Comment by Hypnootize** [comment]
I am fairly sure this can't be fixed sadly, I think its more due to the fact that you are not even supposed to be able to open more than one menu at once (in this case casual and competitive) if you take a look at the default hud you can't really open multiple menus at the same time but instead you have to go back from a menu in order to be able to open another one. 
For my hud I went for a different design making you are able to open more than one menu at once and its probably something that valve didn't intend to be possible therefore some bugs are to be expected.

**Comment by Gensokian** [comment]
Fair enough. I'll close this. Maybe(tm) I'll be reopening it if I got an Idea to pitch ^^

**Comment by Gensokian** [comment]
Short addition, I edited together a new menu aaaand.... well... it doesn't look that good.
![image](https://user-images.githubusercontent.com/9213561/106354629-8d2c5580-62f3-11eb-92a5-5932cb7b2ce5.png)
![image](https://user-images.githubusercontent.com/9213561/106354656-b0ef9b80-62f3-11eb-8740-da1426b504af.png)
