### ISSUE TITLE
bottom left menu icons misaligned

### ISSUE THREAD

**Issue by nanopone** [Hypnootize/hypnotize-hud#42]
i'm on linux, if it matters.
![2021-09-22_20-09-58](https://user-images.githubusercontent.com/49787675/134406760-e1d00d87-d421-476d-a707-ede2e6a40fef.png)

**Comment by Hypnootize** [comment]
A side effect of linux is that fonts are rendered differently than what they would be on windows, often making them bigger in size, I currently have no way of testing the font on linux but in the future I could maybe try resizing the font and see if I can come up with a decent result.

Should hopefully be fixed with the last update!
