### ISSUE TITLE
Extra colon on casual level on main menu

### ISSUE THREAD

**Issue by nifte** [Hypnootize/hypnotize-hud#44]
On the main menu, there seems to be an extra colon on the casual level that doesn't appear on the competitive level.

Comp:
![competetive](https://user-images.githubusercontent.com/9247037/187098386-b3fc090c-3290-4090-bf2a-e6f550fad44b.png)
Casual:
![casual](https://user-images.githubusercontent.com/9247037/187098384-15f7580f-9637-49a9-93e1-102a1f038062.png)

**Comment by Hypnootize** [comment]
That's mostly due to the fact that to make this work I used a only numbers + colon font, for example a normal casual level `[Level: 46 Tier: 2]` will show as `[Level:46:2]` in my HUD and that's how I intended it to be. 

That said I never personally cared enough about the comp level to change this, I never played it and never will, I assume on higher levels it won't even show the number at all since the rank name doesn't include numbers at all iirc, so yeah I'm aware of this but probably won't fix it for now as it would imply redesigning the whole rank desing probably.
