### ISSUE TITLE
Black bars on war paint weapon images

### ISSUE THREAD

**Issue by nifte** [Hypnootize/hypnotize-hud#45]
In 1440p, inspecting items with war paint in game shows a black bar on their images.

![weapon](https://user-images.githubusercontent.com/9247037/187098789-a50734ca-7489-41d6-a722-a4221b6202d2.png)

**Comment by Hypnootize** [comment]
That's also something I'm aware about, this is a side effect of using HD weapon images so the only solution would be to edit each `"inventory_image_type"` to use `"0"` instead of `"1"`, for the one in the screenshot specifically would be [THIS](https://github.com/Hypnootize/hypnotize-hud/blob/master/resource/ui/freezepanel_basic_base.res#L35)

Edit: Seems like I could be wrong, still not sure what the actual cause of this is as I had no luck recreating it.

**Comment by Hypnootize** [comment]
I applied yet another fix (thanks to CriticalFlaw and Whisker) for this with the last update and looks to be fixed
