### ISSUE TITLE
Error texture when using the menu tutorial

### ISSUE THREAD

**Issue by silverfan2020** [Hypnootize/hypnotize-hud#49]
![20230323170054_1](https://user-images.githubusercontent.com/101137098/227279870-57331b76-3a2a-46a2-9a75-788b2bf3fbc4.jpg)
It's self explanatory.

**Comment by Hypnootize** [comment]
The HUD doesn't touch these arrows at all at the moment so I'm not sure why this would happen. 

You could check if you have two .vmt files inside `materials/vgui` called `callout_tail` and `callout_tail_side`, they are not part of the HUD normally but maybe you imported them from somewhere elese and they are referring to a missing .vtf now.

Also side note, even if they do refer to an existing .vtf there is still no way to make them work on protected servers (sv_pure 2) so sometimes the game will give a missing texture instead of reverting them to their default form.

**Comment by silverfan2020** [comment]
it was a one time thing.
