### ISSUE TITLE
[QUESTION] How to change font all around the HUD?

### ISSUE THREAD

**Issue by leofleeo** [Hypnootize/hypnotize-hud#54]
When you change the font using this tutorial: https://github.com/Hypnootize/hypnotizehud/wiki/Fonts, the menus and timers still use the default font. How can I make lato the font to be used all around the hud?

**Comment by Hypnootize** [comment]
I limited where the optional fonts are used since some of them aren't too well suited for some HUD parts.
Now, if you want to use `Lato` everywhere you want to keep the font customization option enabled, like you already do, then open `resource/scheme/font.res` and do a search and replace where you seach for `"Rubik Medium"` and replace it with `"Lato Bold"`, that should enabled `Lato` to be used all around the HUD.

**Comment by leofleeo** [comment]
Thank you!
