### ISSUE TITLE
How to make the custom background appear when loading map

### ISSUE THREAD

**Issue by MuchHigher** [Hypnootize/hypnotize-hud#58]
So I use custom background at the main menu, but are there any settings that can make the background appear at the map loading screen?

**Comment by Hypnootize** [comment]
You need to make a couple of tweaks to `Resource/UI/StatSummary.res` mainly edit the `"Background"` element [HERE](https://github.com/Hypnootize/hypnotizehud/blob/master/resource/ui/statsummary.res#L15-L27)
In short, instead of using a solid background with `FillColor` you can add a path to your custom image like so:
```
"Background"
{
	"ControlName"			"ImagePanel"
	"fieldName"			"Background"
	"xpos"				"0"
	"ypos"				"0"
	"zpos"				"90"
	"wide"				"f0"
	"tall"				"480"
	"visible"			"1"
	"enabled"			"1"
	"scaleimage"			"1"
	"image"				"replay/thumbnails/menu/YOUR IMAGE NAME"
}
```
So obviously instead of `YOUR IMAGE NAME` you will put the .VMT name there, and your custom image files should go inside `materials/vgui/replay/thumbnails/menu`

**Comment by MuchHigher** [comment]
it's pink and black :(

**Comment by Hypnootize** [comment]
Do you have both .vmt and .vtf files inside `materials/vgui/replay/thumbnails/menu`? if it's pink and black it means that the game is not able to find the image and that can be caused by a missing or missplaced .vmt/vtf or the "ïmage" path being wrong.

If you are missing a .vmt you can clone any of the other ones inside the menu folder and then rename it to have the same name as the .vtf file, then open it and update the `"$baseTexture"` path so it links to the .vtf

**Comment by MuchHigher** [comment]
now it's too bright than the original image
original/main menu image:
![29](https://github.com/Hypnootize/hypnotizehud/assets/115716636/8bbf93bb-2aee-4dae-bfae-75e4b1bbb0b0)
replica of the loading screen:
![29 test](https://github.com/Hypnootize/hypnotizehud/assets/115716636/bb6add0a-9d88-42e7-b262-81bfca679221)

**Comment by Hypnootize** [comment]
It might be caused by the VTF edit import settings or something wrong in the .VMT file, hard to tell

**Comment by MuchHigher** [comment]
does it have anything to do with this?
![30](https://github.com/Hypnootize/hypnotizehud/assets/115716636/713f83db-8cbb-4422-bf99-ce6659a7f0d2)

**Comment by Hypnootize** [comment]
Yes, most likely. Try using "UnlitGeneric" instead.

**Comment by MuchHigher** [comment]
Worked like wonders
